config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create] do
  	resources :recommendations, except: [:new, :show, :edit]
  end

  root 'application#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :recommendations

  validates :email, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    render "index"
  end

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  
  include SessionsHelper

  def index
    # recent_media = Instagram.tag_recent_media('fashion')
    @user = User.find(params[:user_id])
    @recommendations = Recommendation.all
    @recommendation = Recommendation.new
    # response = Instagram.get_access_token(params[:code], :redirect_uri => "https://api.instagram.com/v1/tags/nofilter/media/recent?access_token=ACCESS_TOKEN")
    # session[:access_token] = response.access_token
    # @insta_client = Instagram.client(:access_token => session[:access_token])
  end

  def create
    @user = current_user
    @recommendation = Recommendation.new(recommendation_params.merge(user_id: @user.id))

    respond_to do |format|
      if @recommendation.save
        format.js {}
        # format.json { render json: @recommendation }
      else
        format.js { render :error, status: 422 }
      end
    end
  end

  def edit
  end

  # show individual recommendation
  def show
  end

  def update
    @recommendation = Recommendation.find(params[:id])
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.js {}
      else
        format.js { render :error, status: 422 }
      end
    end
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    respond_to do |format|
      if @recommendation.user_id == current_user.id
        @recommendation.destroy
        format.js {}
        # format.json { render json: @recommendation }
      else
        format.js { render :error, status: 422 }
      end
    end
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:name, :cuisine, :city, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
  	@user = User.find_by_username(params[:username])
  	if @user && @user.authenticate(params[:password])
  	  login(@user)
  	  redirect_to "/users/#{@user.id}/recommendations"
  	else
  	  redirect_to '/login'
  	end
  end

  def destroy
  	logout
  	redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  include SessionsHelper

  # def index
  # 	@users = User.all
  # end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
  	@user.password = params[:user][:password]
    @recommendations = Recommendation.all
  	if @user.save
  	  session[:user_id] = @user.id
  	  redirect_to "/users/#{@user.id}/recommendations"
  	else
  	  redirect_to '/users/new'
  	end
  end

  # def show
  #   @user = User.find(params[:id])
  #   @recommendations = Recommendation.all
  # end

  private

  def user_params
  	params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.clear
  end

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Food Recs</h1>
  <p>An online community where friends can post and discover cool food spots</p>
  <p><%= link_to "Login", login_path, :class => "btn btn-primary btn-lg" %> or <%= link_to "Sign Up", new_user_path, :class => "btn btn-primary btn-lg" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodRecommendations</title>
    <%= csrf_meta_tags %>
<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" rel="stylesheet" integrity="sha384-1L94saFXWAvEw88RkpRz8r28eQMvt7kG9ux3DdCqya/P3CfLNtgqzMnyaUa49Pl2" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for([user, recommendation], remote:true, html: {id: "rec-form", class: "red"}) do |f| %>

<%= f.text_field :name, placeholder: "name" %>
<%= f.text_field :cuisine, placeholder: "cuisine" %>
<%= f.text_field :city, placeholder: "city" %>
<%= f.text_field :description, placeholder: "description" %>
<br>
<%= f.submit %>
<% end %>

app/views/recommendations/_recommendation.html.erb
<div id="rec-<%= recommendation.id %>"%>
	Name: <%= recommendation.name %><br>
	Cuisine: <%= recommendation.cuisine %><br>
	City: <%= recommendation.city %><br>
	Description: <%= recommendation.description %><br>
	<% place_url = recommendation.name.gsub(/[ ]/, '+') +  "," + recommendation.city.gsub(/[ ]/, '+') %>
	<iframe width="300" height="300" frameborder="0" style="border:0"
	src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_MAPS_EMBED_KEY"] %>&q=<%= place_url %>"
	allowfullscreen>
	</iframe>
	
	<br>
	<br>

Recommended by: <%= recommendation.user.username %><br>

<% if false %>
<% insta_tags = @insta_client.tag_search(recommendation.name.gsub(/\s+/, '')) %>
<h4>Tag Name = <%= "#{insta_tags[0].name}" %>. Media Count = <%= "#{insta_tags[0].media_count}" %>.</h4><br>
<% for media_item in @insta_client.tag_recent_media(insta_tags[0].name) %>
<img src=<%= "#{media_item.images.thumbnail.url}" %>>
<% end %>
<% end %>


<% if recommendation.user_id == current_user.id %>
<button id=<%="slidedown-#{recommendation.id}"%> class="slidedown">Update</button>
<div id="reveal-<%= recommendation.id %>" style="display:none"><%= render partial: "form", locals: { user: recommendation.user, recommendation: recommendation } %></div>
<%= link_to "Delete", user_recommendation_path(recommendation.user, recommendation), method: 'delete', remote:true %>
<% end %>

<br>
<br>
<br>

</div>

app/views/recommendations/create.js.erb
$("ul").append("<%= j render partial: 'recommendation', locals: {recommendation: @recommendation} %>");

$("#rec-form")[0].reset();

app/views/recommendations/destroy.js.erb
$("#rec-<%= @recommendation.id %>").remove();

app/views/recommendations/error.js.erb
console.log("<%= j @recommendation.errors.full_messages %>")

app/views/recommendations/index.html.erb
<h2>Hey <%= @user.username %>!</h2>

<br>
<br>

<h4>Recommendations:</h4>

<br>

<ul>
<%= render partial: "recommendation", collection: @recommendations %>
</ul>

<br>
<br>

<%= render partial: "form", locals: {user: @user, recommendation: @recommendation} %>

<br>
<br>
<br>
<br>
<br>

<a href="/logout">Logout</a>

app/views/recommendations/update.js.erb
$("#rec-<%= @recommendation.id %>").html("<%= j render partial: 'recommendation', locals: {recommendation: @recommendation} %>");

$("#rec-<%= @recommendation.id %>")[0].reset();

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_for :user, url: '/users' do |f| %>
<%= label :email, 'Email' %></br>
<%= f.text_field :email %></br>
<%= label :username, 'Username' %></br>
<%= f.text_field :username %></br>
<%= label :password, 'Password' %></br>
<%= f.password_field :password %></br>
<%= label :password_confirmation, 'Confirm Password' %></br>
<%= f.password_field :password_confirmation %></br>
<%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h2>Hey <%= @user.username %>!</h2>

<br>
<br>

<h4>Recommendations:</h4>
<% @recommendations.each do |rec| %>
<p>Name: <%= rec.name %></p><br>
<p>Cuisine: <%= rec.cuisine %></p><br>
<p>City: <%= rec.city %></p><br>
<p>Description: <%= rec.description %></p><br>
<% place_url = rec.name.gsub(/[ ]/, '+') +  "," + rec.city.gsub(/[ ]/, '+') %>
<p><iframe width="300" height="300" frameborder="0" style="border:0"
	src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_MAPS_EMBED_KEY"] %>&q=<%= place_url %>"
	allowfullscreen>
</iframe></p><br><br>
<p>Recommended by <%= rec.username %></p>
<br>
<br>
<br>
<% end %>

<br>
<br>

<%= link_to "Recommend a Place", new_recommendation_path %>

<br>
<br>
<br>
<br>
<br>

<a href="/logout">Logout</a>